### ISSUE TITLE
proposition: check available balance for selected pair

### ISSUE THREAD

**Issue by dearkafka** [nelso0/barbotine-arbitrage-bot#2]
it seems the best not to buy every time, but check if the available balance is sufficient

**Comment by nelso0** [comment]
> it seems the best not to buy every time, but check if the available balance is sufficient

This is a good idea, but not necessary, you can just sell the needed amount in usdt before running it, it's not that complicated.

**Comment by dearkafka** [comment]
I agree but I'm more worried about futures as they are more complicated and have a margin

**Comment by dearkafka** [comment]
I agree but I'm more worried about futures as they are more complicated and
have a margin

**Comment by nelso0** [comment]
> I agree but I'm more worried about futures as they are more complicated and have a margin

Please email me, it's not the right place as what you say is not an issue.
To answer, I don't know what you mean because it trades only in spot, there is just one simple short order for the delta-neutral mode.
